import React, { useState } from 'react';
import { FiCopy, FiCheck, FiDownload, FiCpu } from 'react-icons/fi';
import { motion } from 'framer-motion';

interface SummaryCardProps {
  summary: string;
  query: string;
}

export const SummaryCard: React.FC<SummaryCardProps> = ({ summary, query }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    const markdownContent = `# AI Reddit Summary: ${query}\n\n${summary}\n\n*Generated by Reddit Review Analyzer*`;
    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `reddit_summary_${query.replace(/\s+/g, '_').toLowerCase()}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Basic parser for **bold** text and paragraphs
  const renderFormattedSummary = (text: string) => {
    return text.split('\n\n').map((paragraph, pIdx) => {
      const parts = paragraph.split(/(\*\*.*?\*\*)/g);
      return (
        <p key={pIdx} className="mb-4 leading-relaxed text-[var(--text-color)] text-base md:text-lg last:mb-0">
          {parts.map((part, partIdx) => {
            if (part.startsWith('**') && part.endsWith('**')) {
              return (
                <strong key={partIdx} className="font-bold text-reddit-orange dark:text-orange-400">
                  {part.slice(2, -2)}
                </strong>
              );
            }
            return part;
          })}
        </p>
      );
    });
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="glass-panel rounded-2xl p-6 md:p-8 relative overflow-hidden"
    >
      <div className="flex items-center justify-between border-b border-[var(--border-color)] pb-4 mb-6">
        <div className="flex items-center gap-2">
          <FiCpu className="text-reddit-orange text-xl" />
          <h3 className="text-lg font-bold text-[var(--text-color)]">AI Analysis Summary</h3>
        </div>
        
        {/* Actions Button Bar */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex h-9 px-3 items-center gap-1.5 rounded-lg border border-[var(--border-color)] bg-[var(--bg-color)] text-[var(--text-color)] hover:border-reddit-orange text-xs font-medium transition-all duration-200"
            title="Copy to Clipboard"
            id="copy-summary-btn"
          >
            {copied ? (
              <>
                <FiCheck className="text-emerald-500" />
                <span className="text-emerald-500">Copied!</span>
              </>
            ) : (
              <>
                <FiCopy />
                <span>Copy</span>
              </>
            )}
          </button>

          <button
            onClick={handleExport}
            className="flex h-9 px-3 items-center gap-1.5 rounded-lg border border-[var(--border-color)] bg-[var(--bg-color)] text-[var(--text-color)] hover:border-reddit-orange text-xs font-medium transition-all duration-200"
            title="Export as Markdown"
            id="export-summary-btn"
          >
            <FiDownload />
            <span>Export</span>
          </button>
        </div>
      </div>

      <div className="prose prose-slate dark:prose-invert max-w-none">
        {renderFormattedSummary(summary)}
      </div>
    </motion.div>
  );
};
